version: '3.9'

services:
  rustapp:
    container_name: rustapp
    image: rnrifai/rustapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:RNRif@i1212@db:5432/rustapp
    ports:
      - '8090:8090'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RNRif@i1212
      POSTGRES_DB: rustapp
    ports:
      - '5433:5432'  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}